repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.1
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix", "--show-fixes"]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 1ce7e7fa8aa6eda60e54755509a9380b0f1c5d08 # frozen: v0.9.30
    hooks:
      - id: uv-lock
        args: ["--index-url", "https://pypi.org/simple/"]
  - repo: https://github.com/rstcheck/rstcheck
    rev: 77490ffa33bfc0928975ae3cf904219903db755d # frozen: v6.2.5
    hooks:
      - id: rstcheck
        additional_dependencies: ['rstcheck[sphinx]']
        args: ["--report-level", "warning"]
