name: Lint tests

on:
  push:
    branches-ignore:
    - 'release/*'
  pull_request:
env:
  CORE_REPO_SHA: 141a6a2e473ef7f0ec4915dfb71e3c0fa595283e

jobs:
  lint-3_12:
    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        package:
          - "distro"
          - "exporter-prometheus-remote-write"
          - "exporter-richconsole"
          - "instrumentation-aio-pika"
          - "instrumentation-aiohttp-client"
          - "instrumentation-aiohttp-server"
          - "instrumentation-aiopg"
          - "instrumentation-asgi"
          - "instrumentation-asyncio"
          - "instrumentation-asyncpg"
          - "instrumentation-aws-lambda"
          - "instrumentation-boto"
          - "instrumentation-boto3sqs"
          - "instrumentation-botocore"
          - "instrumentation-cassandra"
          - "instrumentation-celery"
          - "instrumentation-confluent-kafka"
          - "instrumentation-dbapi"
          - "instrumentation-django"
          - "instrumentation-elasticsearch"
          - "instrumentation-falcon"
          - "instrumentation-fastapi"
          - "instrumentation-flask"
          - "instrumentation-grpc"
          - "instrumentation-httpx"
          - "instrumentation-jinja2"
          - "instrumentation-kafka-python"
          - "instrumentation-logging"
          - "instrumentation-mysql"
          - "instrumentation-mysqlclient"
          - "instrumentation-psycopg"
          - "instrumentation-psycopg2"
          - "instrumentation-pymemcache"
          - "instrumentation-pymongo"
          - "instrumentation-pymysql"
          - "instrumentation-pyramid"
          - "instrumentation-redis"
          - "instrumentation-remoulade"
          - "instrumentation-requests"
          - "instrumentation-sio-pika"
          - "instrumentation-sqlalchemy"
          - "instrumentation-sqlite3"
          - "instrumentation-starlette"
          - "instrumentation-system-metrics"
          - "instrumentation-threading"
          - "instrumentation-tornado"
          - "instrumentation-tortoiseorm"
          - "instrumentation-urllib"
          - "instrumentation-urllib3"
          - "instrumentation-wsgi"
          - "opentelemetry-instrumentation"
          - "processor-baggage"
          - "propagator-aws-xray"
          - "propagator-ot-trace"
          - "resource-detector-azure"
          - "resource-detector-container"
          - "sdk-extension-aws"
          - "util-http"
        os: [ubuntu-20.04]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install tox
        run: pip install tox
      - name: Cache tox environment
        # Preserves .tox directory between runs for faster installs
        uses: actions/cache@v4
        with:
          path: |
            .tox
            ~/.cache/pip
          key: v7-build-tox-cache-${{ matrix.package }}-${{ hashFiles('tox.ini', 'gen-requirements.txt', 'dev-requirements.txt') }}
      - name: run tox
        run: tox -e lint-${{ matrix.package }}
